name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}
    # - name: Build and push
    #   uses: docker/build-push-action@v5
    #   with:
    #       context: .
    #       push: true
    #       tags:  ${{ secrets.DOCKERHUB_USERNAME }}/image:latest 
    - name: executing remote ssh commands using password
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        EXCLUDE: "/dist/, /node_modules/"
        SCRIPT_BEFORE: |
          whoami


      # uses: appleboy/ssh-action@v1.0.3
      # with:
      #   host: ${{ secrets.HOST }}
      #   username: ${{ secrets.USERNAME }}
      #   key: ${{ secrets.SSH_PRIVATEKEY_RSA }}
      #   port: ${{ secrets.PORT }}

        # host: 159.65.158.200
        # username: root
        # password: "@12Sumimarndi"
        # port: 22
        script: |
          cd /var/www/html/vuetify-fornt
          git pull origin master
          


   





